### ISSUE TITLE
Empty stylesheet

### ISSUE THREAD

**Issue by butaminas** [actengage/vue-credit-card-field#3]
Congrats on making this great Vue component!

Would like to report that the 'vue-credit-card-field.min.css' is empty, therefore, even the example doesn't work properly.

I've included 'vue-credit-card-field.es.min.css' in my project and it seems to be working. What's the difference between these 2 files anyway?

![image](https://user-images.githubusercontent.com/10225960/57849793-ea613a00-77e4-11e9-9ced-d0eedfabb3d6.png)

**Comment by actengage** [comment]
Should be fixed in latest version. It's now named CreditCardField.css. I switched from rollup to Webpack, for better or for worse. Too many issues with Rollup and vue for us. I recommend using Webpack or Rollup and just import the vue component directly and let the build tool handle the css (if possible).
