### ISSUE TITLE
The computed property "errors" is already defined as a prop.

### ISSUE THREAD

**Issue by butaminas** [actengage/vue-credit-card-field#4]
The component works fine but I get this error at startup. Any ideas?
![image](https://user-images.githubusercontent.com/10225960/57850041-9c006b00-77e5-11e9-9d0e-b5129633d74a.png)

**Comment by actengage** [comment]
This should be fixed in the latest v0.3.0 release. The new release has a new import syntax because this repo now houses multiple credit card field UI's. Check out the new UI that is an alternative to the Stripe version. If you want to keep using the old version, its now called `InlineCreditCardField`.

**Comment by smccoy78** [comment]
I'm getting this error using the latest release.

![Screen Shot 2020-10-08 at 8 50 55 PM](https://user-images.githubusercontent.com/2486409/95529103-10721600-09a8-11eb-9595-dceb03c4df92.png)
